#!/bin/bash
# 20-useradd
# vim: set tabstop=4 shiftwidth=4 expandtab:

[ ${DIB_DEBUG_TRACE:-0} -gt 0 ] && set -x
set -eu
set -o pipefail

useradd -g ubuntu -u 1000 -m -d /home/ubuntu -s /bin/bash ubuntu
echo 'ubuntu:ubuntu' | chpasswd -c MD5
echo 'root:root' | chpasswd -c MD5

echo -e "ubuntu\tALL=(ALL)\tNOPASSWD: ALL" > /etc/sudoers.d/ubuntu
chmod 440 /etc/sudoers.d/ubuntu
exit 0
