---
# hosts.yml
# vim: set tabstop=2 shiftwidth=2 expandtab:

all:
  children:
    centos:
      hosts:
        centos10s:
          ansible_connection: local
          dib_release: 10-stream
      vars:
        target_group: centos
    debian:
      hosts:
        debian1215:
          ansible_connection: local
          dib_release: bookworm
        debian1306:
          ansible_connection: local
          dib_release: trixie
      vars:
        target_group: debian
    fedora:
      hosts:
        fedora44:
          ansible_connection: local
          dib_release: "44"
      vars:
        target_group: fedora
    rocky:
      hosts:
        rocky102:
          ansible_connection: local
          dib_release: "10"
      vars:
        target_group: rocky
    ubuntu:
      hosts:
        ubuntu24044:
          ansible_connection: local
          dib_release: noble
        ubuntu26041:
          ansible_connection: local
          dib_release: resolute
      vars:
        target_group: ubuntu

