---
# hosts.yml
# vim: set tabstop=2 shiftwidth=2 expandtab:

all:
  children:
    centos10stream:
      hosts:
        centos10s:
          ansible_connection: local
          dib_release: 10-stream
      vars:
        target_group: centos10stream
    debian:
      hosts:
        debian1304:
          ansible_connection: local
          dib_release: trixie
      vars:
        target_group: debian
    fedora:
      hosts:
        fedora43:
          ansible_connection: local
          dib_release: "43"
      vars:
        target_group: fedora
    ubuntu:
      hosts:
        ubuntu22045:
          ansible_connection: local
          dib_release: jammy
        ubuntu24044:
          ansible_connection: local
          dib_release: noble
      vars:
        target_group: ubuntu

