#!/bin/bash
# 20-useradd
# vim: set tabstop=4 shiftwidth=4 expandtab:

[ ${DIB_DEBUG_TRACE:-0} -gt 0 ] && set -x
set -eu
set -o pipefail

useradd -g debian -u 1000 -m -d /home/debian -s /bin/bash debian
echo 'debian:debian' | chpasswd -c SHA512
echo 'root:root' | chpasswd -c SHA512

echo -e "debian\tALL=(ALL)\tNOPASSWD: ALL" > /etc/sudoers.d/debian
chmod 440 /etc/sudoers.d/debian
exit 0
