#!/bin/bash
# 20-useradd
# vim: set tabstop=4 shiftwidth=4 expandtab:

[ ${DIB_DEBUG_TRACE:-0} -gt 0 ] && set -x
set -eu
set -o pipefail

useradd -g cloud-user -u 1000 -m -d /home/cloud-user -s /bin/bash cloud-user
echo 'cloud-user:cloud-user' | chpasswd -c MD5
echo 'root:root' | chpasswd -c MD5

echo -e "cloud-user\tALL=(ALL)\tNOPASSWD: ALL" > /etc/sudoers.d/cloud-user
chmod 440 /etc/sudoers.d/cloud-user
exit 0
